### ISSUE TITLE
undefined method 'framework' for main:Object

### ISSUE THREAD

**Issue by regsmith** [AXElements/AXElements#23]
```
Failure/Error: require 'ax_elements'

NoMethodError:
  undefined method `framework' for main:Object
# /Users/admin/.rvm/gems/ruby-2.4.1/gems/AXElements-0.8.1/lib/mouse.rb:1:in `<top (required)>'
# /Users/admin/.rvm/gems/ruby-2.4.1/gems/AXElements-0.8.1/lib/accessibility/dsl.rb:3:in `<top (required)>'
# /Users/admin/.rvm/gems/ruby-2.4.1/gems/AXElements-0.8.1/lib/ax_elements.rb:2:in `<top (required)>'
```

**Comment by regsmith** [comment]
a workaround for this is to add the git source in the gemfile.

```ruby
gem 'AXElements', :git => 'https://github.com/AXElements/AXElements.git'
```
